import turtle
turtle.setup(800,600)
window = turtle.Screen()
window.title("Absolute Positioning")
window.exitonclick()
turt =  turtle.getturtle()
turt.hideturtle()
turt.setposition(100,0)
turt.setposition(100,100)
turt.setposition(0,100)
turt.setposition(0,0)